name: Automatically assign issues to Issue Triaging project

on:
    issues:
        types: [opened]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    assign-issue:
        runs-on: ubuntu-latest
        name: Assign to Issue Triaging prjoect
        steps:
            - name: Assign new issues to triaging project
              uses: srggrs/assign-one-project-github-action@1.2.1
              if: github.event.action == 'opened'
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
              with:
                  project: "https://github.com/williamboman/mason.nvim/projects/1"
                  column_name: "Needs triage"

            - name: Create a PR comment
              uses: peter-evans/create-or-update-comment@v1
              if: contains(github.event.issue.labels.*.name, 'new-package-request')
              with:
                token: ${{ secrets.PAT }}
                issue-number: ${{ github.event.issue.number }}
                body: |
                    Hello! Cool! Pull requests are always very welcomed to add new packages. If the distribution of the
                    package is simple, the installation will most likely be so as well (existing package installers may be
                    used for reference!). Otherwise, @williamboman will get around to looking into this ASAP!
